import type { CSSProperties, ReactNode, RefObject } from "react";
import { Box, ChevronDown, Eye, Gauge, ImagePlus, Layers3, RefreshCw, RotateCcw, Sparkles, Video, X } from "lucide-react";
import { FpsInput } from "../../components/FpsInput";
import type { AppSettings, FaceAlignment, TrackingFrame } from "../../types";

export interface RightSidebarProps {
  collapsed: boolean;
  toggleCollapsed: () => void;
  tracking: {
    status: "idle" | "loading" | "ready" | "error"; score: number; label: string; fallbackReason: string;
    delegate: string; cameraReady: boolean; reload: () => void;
  };
  settings: AppSettings;
  updateSetting: <K extends keyof AppSettings>(key: K, value: AppSettings[K]) => void;
  avatarLabel: string;
  calibrating: boolean;
  calibration: {
    neutralFrame: TrackingFrame | null; readiness: FaceAlignment; recordingIdle: boolean;
    trackerReady: boolean; hasFrame: boolean; start: () => void;
  };
  background: {
    url: string | null; name: string; inputRef: RefObject<HTMLInputElement | null>;
    clear: () => void;
  };
  resizeHandle?: ReactNode;
}

export function RightSidebar({ collapsed, toggleCollapsed, tracking, settings, updateSetting, avatarLabel, calibrating, calibration, background, resizeHandle }: RightSidebarProps) {
  return <aside className={`sidebar right-sidebar ${collapsed ? "collapsed" : ""}`}>
    {resizeHandle}
    <button type="button" className="sidebar-collapse-toggle" aria-label={collapsed ? "Expand right sidebar" : "Collapse right sidebar"} title={collapsed ? "Expand right sidebar" : "Collapse right sidebar"} onClick={toggleCollapsed}><ChevronDown size={15} /></button>
    <section className={`panel-section tracking-score tracker-${tracking.status}`}><div className="score-ring" style={{ "--score": `${tracking.score * 3.6}deg` } as CSSProperties}><strong>{tracking.score}</strong><small>%</small></div><div><span>Tracking quality</span><strong>{tracking.label}</strong><small title={tracking.fallbackReason || undefined}>{settings.trackingFps} FPS target · {tracking.delegate}</small><button className="inline-retry tracker-reload" disabled={!tracking.cameraReady} title={tracking.cameraReady ? "Reload the local MediaPipe model and face-tracking worker" : "Connect a camera before reloading the tracker"} onClick={tracking.reload}><RefreshCw size={12} />{tracking.status === "error" ? "Retry tracker" : tracking.status === "loading" ? "Restart loading" : "Reload tracker"}</button></div></section>
    <section className="panel-section"><div className="section-heading"><span>Layers</span><Layers3 size={15} /></div><label className={`toggle-row ${settings.showWebcam ? "is-active" : ""}`}><span><Video size={16} />Webcam<small>{settings.showWebcam ? "ON" : "OFF"}</small></span><input type="checkbox" disabled={calibrating} checked={settings.showWebcam} onChange={(event) => updateSetting("showWebcam", event.target.checked)} /></label><label className={`toggle-row ${settings.showAvatar ? "is-active" : ""}`}><span><Box size={16} />{avatarLabel} avatar<small>{settings.showAvatar ? "ON" : "OFF"}</small></span><input type="checkbox" disabled={calibrating} checked={settings.showAvatar} onChange={(event) => updateSetting("showAvatar", event.target.checked)} /></label><label className={`toggle-row ${settings.showLandmarks ? "is-active" : ""}`}><span><Gauge size={16} />Landmarks<small>{settings.showLandmarks ? "ON" : "OFF"}</small></span><input type="checkbox" disabled={calibrating} checked={settings.showLandmarks} onChange={(event) => updateSetting("showLandmarks", event.target.checked)} /></label><label className={`toggle-row ${settings.mirror ? "is-active" : ""}`}><span><Eye size={16} />Mirror camera + motion<small>{settings.mirror ? "ON" : "OFF"}</small></span><input type="checkbox" disabled={calibrating} checked={settings.mirror} onChange={(event) => updateSetting("mirror", event.target.checked)} /></label></section>
    <section className="panel-section">
      <div className="section-heading"><span>Avatar display</span></div>
      <label className="slider-row"><span>Opacity</span><input type="range" min="0" max="100" value={settings.avatarOpacity * 100} onChange={(event) => updateSetting("avatarOpacity", Number(event.target.value) / 100)} /><output>{Math.round(settings.avatarOpacity * 100)}</output></label>
      <label className="toggle-row"><span>Wireframe</span><input type="checkbox" checked={settings.wireframe} onChange={(event) => updateSetting("wireframe", event.target.checked)} /></label>
      <label className="field-label background-field">Head background
        <select value={settings.backgroundMode} onChange={(event) => { const mode = event.target.value as AppSettings["backgroundMode"]; updateSetting("backgroundMode", mode); if (mode === "image" && !background.url) window.setTimeout(() => background.inputRef.current?.click(), 0); }}>
          <option value="studio">Studio gradient</option><option value="solid">Solid colour</option><option value="image">Custom image</option><option value="transparent">Transparent</option>
        </select>
      </label>
      {settings.backgroundMode === "solid" && <label className="color-field"><span>Background colour</span><input type="color" value={settings.backgroundColor} onChange={(event) => updateSetting("backgroundColor", event.target.value)} /><output>{settings.backgroundColor.toUpperCase()}</output></label>}
      {settings.backgroundMode === "image" && <div className="background-image-controls"><div className="background-image-actions"><button className="secondary-button" onClick={() => background.inputRef.current?.click()}><ImagePlus size={15} />{background.url ? "Replace image" : "Choose image"}</button>{background.url && <button className="icon-button" onClick={background.clear} title="Remove custom background"><X size={14} /></button>}</div><small title={background.name}>{background.name || "No image selected"}</small><label className="slider-row image-zoom"><span>Image zoom</span><input type="range" min="100" max="300" step="1" disabled={!background.url} value={settings.backgroundImageZoom * 100} onChange={(event) => updateSetting("backgroundImageZoom", Number(event.target.value) / 100)} /><output>{Math.round(settings.backgroundImageZoom * 100)}%</output></label><p className="helper-copy">Cover-fit preserves the original aspect ratio, including square images. Zoom changes framing without stretching.</p></div>}
      <label className={`toggle-row ${settings.mouseLightEnabled ? "is-active" : ""}`}><span>Pointer light<small>{settings.mouseLightEnabled ? "ON" : "OFF"}</small></span><input type="checkbox" checked={settings.mouseLightEnabled} onChange={(event) => updateSetting("mouseLightEnabled", event.target.checked)} /></label>
      <label className="slider-row"><span>Light power</span><input type="range" min="0" max="200" disabled={!settings.mouseLightEnabled} value={settings.mouseLightIntensity * 100} onChange={(event) => updateSetting("mouseLightIntensity", Number(event.target.value) / 100)} /><output>{Math.round(settings.mouseLightIntensity * 100)}</output></label>
    </section>
    <section className="panel-section"><div className="section-heading"><span>Neutral calibration</span><small>{calibration.neutralFrame ? "Calibrated" : "Recommended"}</small></div><p className="helper-copy">Face forward with a relaxed expression. Calibration temporarily shows camera-only, then restores your previous layers. It zeros resting facial channels, head orientation, XYZ translation, and relative scale.</p><div className={`face-readiness ${calibration.readiness.status}`}><i /><span>{calibration.readiness.message}</span></div><button className="primary-button wide" onClick={calibration.start} disabled={calibrating || !calibration.recordingIdle || !calibration.trackerReady || !calibration.hasFrame}><Sparkles size={16} />{calibrating ? "Verifying position…" : calibration.neutralFrame ? "Recalibrate" : "Calibrate neutral"}</button></section>
    <section className="panel-section">
      <div className="section-heading"><span>Tracking motion</span></div>
      <FpsInput label="MediaPipe FPS" value={settings.trackingFps} onChange={(value) => updateSetting("trackingFps", value)} />
      <label className={`toggle-row ${settings.trackingSmoothingEnabled ? "is-active" : ""}`}><span>Facial smoothing<small>{settings.trackingSmoothingEnabled ? "ON" : "OFF"}</small></span><input type="checkbox" checked={settings.trackingSmoothingEnabled} onChange={(event) => updateSetting("trackingSmoothingEnabled", event.target.checked)} /></label>
      <label className="slider-row smoothing-slider"><span>Face strength</span><input type="range" min="0" max="100" step="1" disabled={!settings.trackingSmoothingEnabled} value={settings.trackingSmoothing * 100} onChange={(event) => updateSetting("trackingSmoothing", Number(event.target.value) / 100)} /><output>{Math.round(settings.trackingSmoothing * 100)}%</output></label>
      <label className={`toggle-row ${settings.motionSmoothingEnabled ? "is-active" : ""}`}><span>Head motion smoothing<small>{settings.motionSmoothingEnabled ? "ON" : "OFF"}</small></span><input type="checkbox" checked={settings.motionSmoothingEnabled} onChange={(event) => updateSetting("motionSmoothingEnabled", event.target.checked)} /></label>
      <label className="slider-row smoothing-slider"><span>Motion strength</span><input type="range" min="0" max="100" step="1" disabled={!settings.motionSmoothingEnabled} value={settings.motionSmoothing * 100} onChange={(event) => updateSetting("motionSmoothing", Number(event.target.value) / 100)} /><output>{Math.round(settings.motionSmoothing * 100)}%</output></label>
      <label className="slider-row smoothing-slider"><span>Mouth dead zone</span><input type="range" min="0" max="100" step="1" value={settings.mouthDeadZone * 100} onChange={(event) => updateSetting("mouthDeadZone", Number(event.target.value) / 100)} /><output>{Math.round(settings.mouthDeadZone * 100)}%</output></label>
      <p className="helper-copy smoothing-help">Face filtering is intentionally stronger; head motion uses a lighter independent filter. Small isolated one-frame twitches are rejected, while sustained and fast deliberate movement remains responsive. 0% is raw.</p>
      <details className="advanced-expression head-pose-settings"><summary><RotateCcw size={15} />Face-only head rotation</summary><label className={`toggle-row ${settings.headRotationEnabled ? "is-active" : ""}`}><span>Rotate from face<small>{settings.headRotationEnabled ? "ON" : "OFF"}</small></span><input type="checkbox" checked={settings.headRotationEnabled} onChange={(event) => updateSetting("headRotationEnabled", event.target.checked)} /></label><label className="slider-row"><span>Yaw</span><input type="range" min="0" max="150" step="1" disabled={!settings.headRotationEnabled} value={settings.headYawStrength * 100} onChange={(event) => updateSetting("headYawStrength", Number(event.target.value) / 100)} /><output>{Math.round(settings.headYawStrength * 100)}%</output></label><label className="slider-row"><span>Pitch</span><input type="range" min="0" max="150" step="1" disabled={!settings.headRotationEnabled} value={settings.headPitchStrength * 100} onChange={(event) => updateSetting("headPitchStrength", Number(event.target.value) / 100)} /><output>{Math.round(settings.headPitchStrength * 100)}%</output></label><label className="slider-row"><span>Roll</span><input type="range" min="0" max="150" step="1" disabled={!settings.headRotationEnabled} value={settings.headRollStrength * 100} onChange={(event) => updateSetting("headRollStrength", Number(event.target.value) / 100)} /><output>{Math.round(settings.headRollStrength * 100)}%</output></label><label className="slider-row"><span>Dead zone</span><input type="range" min="0" max="10" step="0.25" disabled={!settings.headRotationEnabled} value={settings.headRotationDeadZone} onChange={(event) => updateSetting("headRotationDeadZone", Number(event.target.value))} /><output>{settings.headRotationDeadZone.toFixed(1)}°</output></label><label className="slider-row"><span>Pose smoothing</span><input type="range" min="0" max="100" step="1" disabled={!settings.headRotationEnabled} value={settings.headRotationSmoothing * 100} onChange={(event) => updateSetting("headRotationSmoothing", Number(event.target.value) / 100)} /><output>{Math.round(settings.headRotationSmoothing * 100)}%</output></label><p className="helper-copy">Uses MediaPipe's facial transform first and face landmarks as a fallback. It does not depend on shoulders or torso pose.</p></details>
    </section>
  </aside>;
}
